# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:cs.*'

# 検索キーワード
keywords:
        Simulated annealing: 4
        quantum annealing: 4
        svm: 4
        perceptron: 2
        ising: 2
        binary: 2
        neural network: 1
        
# 通知の閾値
score_threshold: 3
