# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:cs.*'

# 検索キーワード
keywords:
        simulated annealing: 4
        quantum annealing: 4
        non-convex: 4
        Wolfe　duality: 4
        perceptron: 2
        ising: 2
        binary: 2
        combinatorial optimization: 2
        
# 通知の閾値
score_threshold: 3
