# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:cs.*'

# 検索キーワード
keywords:
        quantum annealing: 3
        svm: 3
        perceptron: 2
        ising: 1
        deep: 1

# 通知の閾値
score_threshold: 2
